language: php

php:
  - 7.1
  - 7.2

install:
  - pecl install protobuf-3.5.1
  - composer install --prefer-dist --no-interaction --dev

script:
  - vendor/bin/phpspec run --config=phpspec.yml --no-interaction
