<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: test.proto

namespace GPBMetadata;

class Test
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a4f0a0a746573742e70726f746f120474657374221f0a0c48656c6c6f52" .
            "657175657374120f0a076d6573736167651801200128094212ca020f4170" .
            "705c50726f746f5c5374756273620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

